language: php
php:
- '7.2'
branches:
  only:
  - master
env:
- GLPI_PLUGIN_NAME=`echo $TRAVIS_BUILD_DIR | sed -e 's/^.*-//'` TRAVIS_TAG=`git for-each-ref
  --sort=-taggerdate --count=1 --format '%(refname:short)' refs/tags` RELEASE_NAME=`git
  for-each-ref --sort=-taggerdate --count=1 --format '%(contents:subject)' refs/tags`
  RELEASE_BODY=`git for-each-ref --sort=-taggerdate --count=1 --format '%(contents:body)'
  refs/tags`
install: true
script: true
after_success:
- tar --transform "s%^%$GLPI_PLUGIN_NAME/%" --show-transformed -zcvf $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz
  front inc locales sql $GLPI_PLUGIN_NAME.png *.svg *.xml *.php INSTALL.md LICENSE
  README.md
deploy:
  provider: releases
  token:
    secure: yHLFb2ov0eEWljgqopvxYOxMyOGLBUt88HCgNyVBOmhTC9LxOg8ksCSPFbnNpF7yrTqYD30n9HuH64rNPxo+us94VDyAPFoVo3lOFhrAGmAp4Ge7Fq6pZn+kfmyK5sNAHMiFoS8rfCU33vaLG/y+dvCIq8Z3ukGI6ciFfbeQh7eBYgJVtK27m5xb3H0FXXbX8NxmPbvv54Z4UW+To5KF/uMUe6BZvVZRB43GeWlTb7LlWlKrZZoXXc7eWUbvKrP7+TuADbzsVhm2VRfmiw0iHma1eoXd+MIZPDoQboY83VlV5YasXek9nGcCpdoXVUrMw5fgOywiajVfnnXJGImVioQ5Vg+JzCn1zSZl+VY8gNfQpQjkmrL/PwW0EQCyycKdMBHFd28XO9Ls7bYuDMc6Ghmrx6EbSvQDLR4hGDhWWfRhm7dfBMX2rJGZbEHuf204sCzwFkUb0GL0Lmvd4Cme5zbIBL0ilMqkSPZZy606rGMULqVxqELHW+9rQamPnDmw+pvkVFctwk1JCCfDfOrVcUZp7zbW+wdsJO6eKq+klGWU0isaFjHQ7pc77/9RZQlCcwrJB1aiK5oeDwf6+4VVVi6S0Tg0gphJrQbEAcwbyQbcvWDH3fMCaN/fJobYonz6nbvc0appCwPV6/JcfM3HkloyxMhwG92qGRVkvNYWuM8=
  skip_cleanup: true
  file: $GLPI_PLUGIN_NAME-$TRAVIS_TAG.tar.gz
  name: $RELEASE_NAME
  release_notes: $RELEASE_BODY
  prerelease: false
  on:
    repo: ericferon/glpi-$GLPI_PLUGIN_NAME
    tags: true
